version: 2
jobs:
    build:
        branches:
            only:
                develop
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - run: echo "A first hello"
            - run: python verbs_generator.py
            - run: git --version
